"""Generate the consolidated Atlas asset catalog (Sprint 7, ADR-016).

The catalog is *derived* from the two authoritative sources (dbt meta + the
non-dbt registry). It is regenerated, never hand-edited. CI checks that the
committed catalog matches a fresh generation so the two never drift.

Usage:
    python -m atlas.governance.catalog generate
    python -m atlas.governance.catalog check
"""

from __future__ import annotations

import argparse
import json
import sys
from typing import Any

from atlas.governance.registry import (
    atlas_root,
    build_asset_index,
    load_policy,
    validate_governance,
)

GENERATED_JSON = "governance/generated/catalog.json"
GENERATED_MD = "governance/generated/catalog.md"


def build_catalog() -> dict[str, Any]:
    policy = load_policy()
    index = build_asset_index()
    assets = []
    for asset_id in sorted(index):
        record = {k: v for k, v in index[asset_id].items() if not k.startswith("_")}
        record["asset_id"] = asset_id
        record["origin"] = index[asset_id].get("_origin", "unknown")
        assets.append(record)
    by_type: dict[str, int] = {}
    by_class: dict[str, int] = {}
    for asset in assets:
        by_type[asset.get("asset_type", "?")] = by_type.get(asset.get("asset_type", "?"), 0) + 1
        by_class[asset.get("classification", "?")] = by_class.get(asset.get("classification", "?"), 0) + 1
    return {
        "generator": "atlas.governance.catalog",
        "policy_version": policy.get("version"),
        "asset_count": len(assets),
        "counts_by_type": dict(sorted(by_type.items())),
        "counts_by_classification": dict(sorted(by_class.items())),
        "assets": assets,
    }


def _render_markdown(catalog: dict[str, Any]) -> str:
    lines = [
        "# Atlas Generated Asset Catalog",
        "",
        "> Generated by `python -m atlas.governance.catalog generate`. Do not edit by hand.",
        "",
        f"Total assets: **{catalog['asset_count']}**",
        "",
        "| asset_id | type | owner | classification | retention | lifecycle | contract | origin |",
        "| --- | --- | --- | --- | --- | --- | --- | --- |",
    ]
    for a in catalog["assets"]:
        lines.append(
            f"| `{a['asset_id']}` | {a.get('asset_type', '')} | {a.get('technical_owner', '')} "
            f"| {a.get('classification', '')} | {a.get('retention_class', '')} "
            f"| {a.get('lifecycle_status', '')} | {a.get('contract_version', '')} "
            f"| {a.get('origin', '')} |"
        )
    lines.append("")
    return "\n".join(lines)


def write_catalog() -> dict[str, Any]:
    catalog = build_catalog()
    root = atlas_root()
    json_path = root / GENERATED_JSON
    md_path = root / GENERATED_MD
    json_path.parent.mkdir(parents=True, exist_ok=True)
    json_path.write_text(json.dumps(catalog, indent=2, sort_keys=True) + "\n", encoding="utf-8")
    md_path.write_text(_render_markdown(catalog), encoding="utf-8")
    return catalog


def _committed_matches() -> bool:
    root = atlas_root()
    json_path = root / GENERATED_JSON
    if not json_path.exists():
        return False
    fresh = json.dumps(build_catalog(), indent=2, sort_keys=True) + "\n"
    return json_path.read_text(encoding="utf-8") == fresh


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Atlas governance catalog")
    parser.add_argument("command", choices=["generate", "check"])
    args = parser.parse_args(argv)

    errors = validate_governance()
    if errors:
        print("GOVERNANCE INVALID:", file=sys.stderr)
        for e in errors:
            print(f"  - {e}", file=sys.stderr)
        return 1

    if args.command == "generate":
        catalog = write_catalog()
        print(f"catalog generated: {catalog['asset_count']} assets -> {GENERATED_JSON}")
        return 0

    # check
    if not _committed_matches():
        print(
            "GOVERNANCE DRIFT: committed catalog is stale; run `python -m atlas.governance.catalog generate`",
            file=sys.stderr,
        )
        return 1
    print("governance catalog matches sources")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
